import type { UnrecognisedTitleChange } from "@/graphql/query/titleChanges";

/** Sample dogs for UI demo — no API calls, no database changes. */
export const DEMO_TITLE_CHANGES: UnrecognisedTitleChange[] = [
  {
    dogId: "demo-00000000-0000-4000-8000-000000000001",
    musherId: "demo-musher-001",
    dogName: "DEMO-SD",
    pedigreeName: "Demo Kennel's First Title",
    nzfssNo: "DEMO/001/SD",
    ownerName: "Demo Musher One",
    breed: "Siberian Husky",
    previousTitle: "None",
    newTitle: "Sled Dog",
    previousTitleCode: undefined,
    newTitleCode: "SD",
    points: 52,
    events: 6,
  },
  {
    dogId: "demo-00000000-0000-4000-8000-000000000002",
    musherId: "demo-musher-002",
    dogName: "DEMO-SDX",
    pedigreeName: "Demo Kennel's Excellence",
    nzfssNo: "DEMO/002/SDX",
    ownerName: "Demo Musher Two",
    breed: "Siberian Husky",
    previousTitle: "Sled Dog",
    newTitle: "Sled Dog Excellence",
    previousTitleCode: "SD",
    newTitleCode: "SDX",
    points: 94,
    events: 11,
  },
  {
    dogId: "demo-00000000-0000-4000-8000-000000000003",
    musherId: "demo-musher-003",
    dogName: "DEMO-SDCH",
    pedigreeName: "Demo Kennel's Champion",
    nzfssNo: "DEMO/003/SDCH",
    ownerName: "Demo Musher Three",
    breed: "Siberian Husky",
    previousTitle: "Sled Dog Excellence",
    newTitle: "Sled Dog Champion",
    previousTitleCode: "SDX",
    newTitleCode: "SDCh",
    points: 210,
    events: 18,
  },
  {
    dogId: "demo-00000000-0000-4000-8000-000000000004",
    musherId: "demo-musher-001",
    dogName: "DEMO-LEAP",
    pedigreeName: "Demo Kennel's Leap",
    nzfssNo: "DEMO/004/LEAP",
    ownerName: "Demo Musher One",
    breed: "Siberian Husky",
    previousTitle: "None",
    newTitle: "Sled Dog Excellence",
    previousTitleCode: undefined,
    newTitleCode: "SDX",
    points: 102,
    events: 9,
  },
];
